YAML

name: My First Pipeline

'on':
  push:
    branches:
      - master
      - cicd-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Pipeline is working!"
